#ifndef _STM_CONST_H_
#define _STM_CONST_H_

#define TABLE_NAME_MAX_SIZE 64
#define COLUMN_NAME_MAX_SIZE 64
#define MAX_COLS_SUPPORTED_PER_TABLE 32
#define MAX_CHILD_PER_SCHEMA_TABLE 4
#define MAX_CHILD_PER_RDBMS_TABLE 4
#define MAX_CHILD_PER_CATALOG_TABLE 4


#endif // _STM_CONST_H_
